### ISSUE TITLE
error when trying to run

### ISSUE THREAD

**Issue by pizzav-xyz** [elouangrimm/InfiniteBot#1]
when i run python main.py i get this error

Traceback (most recent call last):
  File "C:\Users\******\Downloads\InfiniteBot-main\InfiniteBot-main\main.py", line 2, in <module>
    import craft
  File "C:\Users\******\Downloads\InfiniteBot-main\InfiniteBot-main\craft.py", line 4, in <module>
    from infinitecraft import InfiniteCraft
ModuleNotFoundError: No module named 'infinitecraft'

C:\Users\******\Downloads\InfiniteBot-main\InfiniteBot-main>python main.py
Traceback (most recent call last):
  File "C:\Users\******\Downloads\InfiniteBot-main\InfiniteBot-main\main.py", line 2, in <module>
    import craft
  File "C:\Users\******\Downloads\InfiniteBot-main\InfiniteBot-main\craft.py", line 4, in <module>
    from infinitecraft import InfiniteCraft
ModuleNotFoundError: No module named 'infinitecraft'

**Comment by uraniumchonk** [comment]
`pip install infinite-craft
`
`pip install termcolor
`

run with `py -X utf8 main.py`

**Comment by pizzav-xyz** [comment]
> ``
> 
> run with `py -X utf8 main.py`

![image](https://github.com/elouangrimm/InfiniteBot/assets/103120356/5fc8dd05-191a-453b-b823-ccc1e38d23f8)
![image](https://github.com/elouangrimm/InfiniteBot/assets/103120356/dac4fcb4-8840-41b6-ac9e-3026c8520d55)

**Comment by stuffed18** [comment]
Run 
pip install infinite-craft 
pip install termcolor 
py -X utf8 craft.py 

Works for me

**Comment by Lord-Funion** [comment]
> Run pip install infinite-craft pip install termcolor py -X utf8 craft.py
> 
> Works for me

------------------------ Starting Random Run ------------------------

2024-11-23 14:39:12 WARNING  [INFINITE CRAFT] Closed InfiniteCraft session
Traceback (most recent call last):
  File "F:\InfiniteBot-main\main.py", line 29, in <module>
    asyncio.run(craft.main())
    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\lordfunion\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\lordfunion\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\lordfunion\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "F:\InfiniteBot-main\craft.py", line 13, in main
    result = await game.pair(game.discoveries[i], game.discoveries[j])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lordfunion\AppData\Local\Programs\Python\Python313\Lib\site-packages\infinitecraft\infinitecraft.py", line 309, in pair
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\lordfunion\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client_reqrep.py", line 1135, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url='https://neal.fun/api/infinite-craft/pair?first=Pineapple+Icebot&second=Duck+Curry'

**Comment by elouangrimm** [comment]
Hmmmm... Sorry I have not seen this thread, it's been almost a year since I have visited this project!  I have had this AsyncIO error before, and I fixed it somehow... It could just be an Infinite Craft server issue, but I will try to find out a fix, then will get back to y'all!

**Comment by Lord-Funion** [comment]
thanks

**Comment by elouangrimm** [comment]
I'm pretty sure that this is the same problem as [this](https://github.com/sqdnoises/infinite-craft/issues/2) GitHub issue for the Python module... Possibly watch that one to see if there is a fix later?

**Comment by sqdnoises** [comment]
just an update, the library has been updated to version 1.2.0 and this error has been fixed!
